spring:
    jpa:
        hibernate:
            naming:
                physical-strategy: org.hibernate.boot.model.naming.CamelCaseToUnderscoresNamingStrategy
        generate-ddl: false
        open-in-view: false
        properties:
            hibernate:
                default_batch_fetch_size: 100
                jdbc:
                    batch_size: 100
            jakarta:
                persistence:
                    sharedCache:
                        mode: ENABLE_SELECTIVE
    sql:
        init:
            mode: embedded

---
spring:
    config:
        activate:
            on-profile: local-database
    jpa:
        hibernate:
            ddl_auto: create
        generate-ddl: true
        defer-datasource-initialization: true
    datasource:
        url: jdbc:h2:mem:localdb
        driver-class-name: org.h2.Driver
        username: sa
        password:
    h2:
        console:
            enabled: true

---
spring:
    config:
        activate:
            on-profile: test-database
    jpa:
        hibernate:
            ddl_auto: create
        generate-ddl: true
        defer-datasource-initialization: true
    datasource:
        url: jdbc:h2:mem:testdb;MODE=MSSQLServer
        driver-class-name: org.h2.Driver
        username: sa
        password:
    h2:
        console:
            enabled: true
    sql:
        init:
            mode: never

---
spring:
    config:
        activate:
            on-profile: dev-database
    jpa:
        hibernate:
            ddl_auto: create
        generate-ddl: true
        defer-datasource-initialization: true
    datasource:
        url: jdbc:h2:mem:testdb;MODE=MSSQLServer
        driver-class-name: org.h2.Driver
        username: sa
        password:
    h2:
        console:
            enabled: true
    sql:
        init:
            mode: never
