logging:
    config: classpath:logback-spring.xml
    charset:
        console: UTF-8
        file: UTF-8
    pattern:
        console: '[%d{HH:mm:ss.SSS}][%highlight(%-5level)][%-30thread{30}][%-60logger{60}:%-4L][%X{traceId}-%X{spanId}] - %m%n'
        file: '[%d][%-5level][%t][%-10logger{10}:%L][%X{traceId}-%X{spanId}] - %m%n'
    logback:
        rollingpolicy:
            max-history: 60
            max-file-size: 2GB

---
spring:
    config:
        activate:
            on-profile: trace-logging

logging:
    level:
        root: trace
        com.multimodule: trace
---
spring:
    config:
        activate:
            on-profile: debug-logging

logging:
    level:
        root: debug
        com.multimodule: debug
---
spring:
    config:
        activate:
            on-profile: info-logging

logging:
    level:
        root: info
        com.multimodule: info
---
spring:
    config:
        activate:
            on-profile: local-server

logging:
    file:
        path: ./logs

---
spring:
    config:
        activate:
            on-profile: test-server

logging:
    file:
        name: none

---
spring:
    config:
        activate:
            on-profile: dev-server

logging:
    file:
        path: /home/log/dev-admin-web

---
spring:
    config:
        activate:
            on-profile: database-logging
    jpa:
        properties:
            show-sql: true
            hibernate:
                format-sql: true