spring:
    application:
        name: admin-web

    config:
        import:
            - classpath:config/application-logging.yml
            - classpath:config/application-profiles.yml
            - classpath:config/application-server.yml
            - classpath:config/application-thymeleaf.yml
            - classpath:config/application-web.yml

logging:
    file:
        name: admin-web
